config/routes.rb
Rails.application.routes.draw do
  get 'waiting', to: 'static_pages#waiting'
  get '/game_size', to: 'static_pages#game_size'
  get '/rule', to: 'static_pages#rule'
  get '/leaderboard', to: 'static_pages#leaderboard'
  resources :games, only: [:show, :index, :create]
  resources :sessions, only: [:new, :create, :index]
  resource :session, only: [:destroy]
  resources :users
  root'sessions#new'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_authentication

  def size
  end

  def rule
  end

  def game
  end

  def waiting
  end

  def Leaderboard
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/game.html.slim
.container.flex_column
    form action="/game" method="POST" id="request_form"
      a.flex_row href="/settings"
        img alt="settings icon" src="assets/settings_icon_small.png"
      label.flex_row for="asked_player"
        .avatar_container
          img alt="opponent avatar image" src="assets/blank_avatar.png"
          .avatar_name opponent_name
          .avatar_sets Sets: opponents.sets_count
        - opponents.hand.each do |card|
            img alt="back of card image" src="assets/card_back.png"
      input.hidden name="asked_player" type="radio" id="asked_player" value="#{opponent_name}" required=""
    - if (go_fish == true)
      form.flex_row.settings__container action="/fish" method="post" id="fish_form"
        button type="submit" name="asked_card" value="#{card.rank}"
          img.game__img--deck alt="deck image" src="assets/deck.png"
    - else
      .flex_row.settings__container for="go_fish_draw"
        img.game__img--deck alt="deck image" src="assets/deck.png"
    .flex_row.settings__container
      h1.game__message--box #{message}
    .flex_row.settings__container
      .avatar_container
        img alt="self avatar image" src="assets/blank_avatar.png"
        .avatar_name #{username}
        .avatar_sets Sets: #{current_user.sets_count}
      - current_user.hand.each do |card|
        button type="submit" name="asked_card" value="#{card.rank}" form="request_form"
          img alt="#{card.rank} of #{card.suit}" src="assets/#{card.to_s}.png"

app/views/static_pages/game_size.html.slim
.container.flex_column
  .navigation__container.flex_row
    = link_to(image_tag("back_arrow.png", alt: "chevron_left icon"), sessions_path, method: 'delete', class: 'navigation__item navigation__item--back')
    h1.navigation__title Number of Players
    = link_to(image_tag("settings_icon_small.png", alt: "settings icon"), users_path, method: 'get', class: 'navigation__item navigation__item--settings')
  = form_for(:game, url: games_path, html: {class: "main_menu__container flex_column"}) do |f|
    = f.submit "2 Players", class: "menu__buttons", :name => "game_size"
    = f.submit "3 Players", class: "menu__buttons", :name => "game_size"
    = f.submit "4 Players", class: "menu__buttons", :name => "game_size"
    = f.submit "5 Players", class: "menu__buttons", :name => "game_size"

app/views/static_pages/leaderboard.html.slim
.container.flex_column
  .navigation__container.flex_row
    = link_to(image_tag("back_arrow.png", alt: "chevron_left icon"), sessions_path, method: 'get', class: 'navigation__item navigation__item--back')
    h1.navigation__title ="High Score"
    = link_to(image_tag("settings_icon_small.png", alt: "settings icon"), users_path, method: 'get', class: 'navigation__item navigation__item--settings')

app/views/static_pages/rule.html.slim
body.reverse
  .container.flex_column
    .navigation__container.flex_row
      = link_to(image_tag("blue_back_arrow.png", alt: "chevron_left icon"), sessions_path, method: 'get', class: 'navigation__item navigation__item--back')
      h1.navigation__title How to Play
      = link_to(image_tag("blue_settings_icon.png", alt: "settings icon"), users_path, method: 'get', class: 'navigation__item navigation__item--settings')
    .settings__container
      h1 OBJECT OF THE GAME
      p
        | The goal is to win the most "sets" of cards. A set is any
          four of a kind, such as four kings, four aces, and so on.

      h1 RANK OF CARDS
      p
        | The cards rank from ace (high) to two (low). The suits are not
          important, only the card numbers are relevant, such as two 3s,
          two 10s, and so on.

      h1 THE DEAL
      p
        | Any player deals one card face up to each player. The player with the
          lowest card is the dealer. The dealer shuffles the cards, and the
          player on his right cuts them.

          The dealer completes the cut and deals the cards clockwise one at a
          time, face down, beginning with the player to his left. If two or three
          people are playing, each player receives seven cards. If four or five
          people are playing, each receives five cards. The remainder of the pack
          is placed face down on the table to form the stock.

      h1 THE PLAY
      p
        | The player to the left of the dealer looks directly at any opponent and
          says, for example, "Give me your kings," usually addressing the opponent
          by name and specifying the rank he wants, from ace down to two. The
          player who is "fishing “must have at least one card of the rank he asked
          for in his hand. The player who is addressed must hand over all the
          cards requested. If he has none, he says, "Go fish!" and the player who
          made the request draws the top card of the stock and places it in his
          hand.

          If a player gets one or more cards of the named rank he asked for, he
          is entitled to ask the same or another player for a card. He can ask
          for the same card or a different one. So long as he succeeds in getting
          cards (makes a catch), his turn continues. When a player makes a catch,
          he must reveal the card so that the catch is verified. If a player gets
          the fourth card of a set, he shows all four cards, places them on the
          table face up in front of him, and plays again.

          If the player goes fishing without "making a catch" (does not receive a
          card he asked for), the turn passes to his left.

          The game ends when all thirteen sets have been won. The winner is the
          player with the most sets. During the game, if a player is left without
          cards, he may (when it's his turn to play), draw from the stock and
          then ask for cards of that rank. If there are no cards left in the
          stock, he is out of the game.

app/views/static_pages/settings.html.slim
.container.flex_column
  .navigation__container.flex_row
    a.navigation__item.navigation__item--back href="#"
      = image_tag "back_arrow.png", alt: "chevron_left icon" 
    h1.navigation__title Settings
    a.navigation__item.navigation__item--settings href="/settings"
      = image_tag "settings_icon_small.png", alt: "settings icon"
  .settings__container
    button.settings__button--quit type="button"
      a href="#"  Quit Current Game
    p.settings__item Username:
    p.settings__item Language:
    p.settings__item Default Game Size:
    p.settings__item Hand Order:
    p.settings__item
      | Game Music:
      a href="#"
        img alt=("sound icon") src="assets/sound.png"

app/views/static_pages/waiting.html.slim
.container.flex_column
  h1.waiting__box Waiting for one more player to join the Game...
  img alt=("waiting timer icon") src="assets/timer_icon.png"